export enum Gender {
  FTM_TRANSMAN = "Transgender Man (FTM)",
  CISGENDER_WOMAN = "Cisgender Woman",
  CISGENDER_MAN = "Cisgender Man",
  NON_BINARY = "Non-Binary",
}

export enum RelationshipGoal {
  LONG_TERM = "Long-Term Relationship",
  CASUAL = "Casual Dating & fun",
  FRIENDSHIP = "Friendship & Community",
  OPEN_TO_CONNECTIONS = "Open to any connection",
}

export interface Profile {
  id: string;
  name: string;
  age: number;
  gender: Gender | string;
  pronouns: string;
  bio: string;
  interests: string[];
  goals: RelationshipGoal;
  location: string;
  distanceMiles?: number;
  profession?: string;
  education?: string;
  avatarSeed: string; // Used for customized avatars (or pixel illustration style)
  avatarBgColor: string; // Beautiful gradients
  transitionStageShared?: string; // Optional transparent notes (e.g., "Pre-op, fully out", "On T, post-top", "Just being myself!")
  openToAnsweringQuestions?: "happy_to_share" | "prefer_no_invasive_questions" | "only_if_matched_and_close";
  verificationStatus: "verified" | "unverified";
}

export interface Match {
  id: string;
  partnerProfile: Profile;
  latestMessage?: string;
  timestamp: string;
  unreadCount: number;
}

export interface Message {
  id: string;
  senderId: string;
  text: string;
  timestamp: number;
  aiSuggested?: boolean; // Label so they can see if it was generated by their wingman coach
  status?: "sent" | "read";
}

export interface GuideArticle {
  id: string;
  title: string;
  category: "Ally Guidance" | "Terminology" | "Safety & Transition" | "Success Stories";
  excerpt: string;
  content: string;
  iconName: string;
}
